name: C# Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Analyze code with StyleCop
      run: dotnet add package StyleCop.Analyzers --version 1.2.0
      continue-on-error: true

    - name: Analyze code with Roslyn Analyzers
      run: dotnet add package Microsoft.CodeAnalysis.FxCopAnalyzers --version 3.3.0
      continue-on-error: true

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run code analysis
      run: dotnet analyze --verbosity diagnostic
