name: ASP.NET Check Style
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Install StyleCop.Analyzers
      run: dotnet add package StyleCop.Analyzers --version 1.2.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Analyze code with StyleCop
      run: dotnet analyze --verbosity diagnostic
